ajuda: "
&6&lAJUDA \n
&eOlá bem vindo ao nosso mundo \n
&eEsse mundo é repleto de Aventuras \n
&etalvez para um novato seja complicado \n
&emas fizemos um guia especial para você\n
&euse &2/guia &epara pegar o guia completo \n
&e \n
&ePrecisa de mais ajuda? use &3/discord \n
"
discord: "&3&lConvite: &ehttps://discord.gg/CDVVjCVdfZ"

entrou: "§aVocê logou com sucesso"
erroSenha: "§cVocê digitou a senha errada, tente novamente"
estaLogado: "§aVocê ja está logado"